"""Reporting agent: turns the run ledger into a stakeholder-readable report.

Live mode uses the cheap model (report writing is pure text generation);
mock mode renders a deterministic template - same sections, no LLM.
"""

import json
from datetime import UTC, datetime

from lakekeeper.agents.context import AgentContext
from lakekeeper.agents.state import PipelineRunState

REPORT_SYSTEM = (
    "You are the reporting agent of 'Lakekeeper', a banking lakehouse operated by agents. "
    "Write a concise markdown run report for data stakeholders from the run ledger JSON: "
    "an executive summary (2-3 sentences), a per-step results table, data-quality findings "
    "and the actions taken (with agent rationales), the reconciliation verdict, and - only "
    "if something needs human follow-up - a short 'Action required' section. Be factual; "
    "every number must come from the ledger."
)


def _ledger(state: PipelineRunState) -> dict:
    return {
        "run_id": state["run_id"],
        "run_date": state["run_date"],
        "status": state.get("status", "running"),
        "steps_completed": state.get("completed", []),
        "dq_reports": state.get("dq_reports", []),
        "decisions": state.get("decisions", []),
        "failures": state.get("failures", []),
        "quarantined_total": state.get("quarantined_total", 0),
        "reconciliation": state.get("reconciliation"),
        "verdict": state.get("verdict"),
    }


def _template_report(ledger: dict) -> str:
    lines = [
        f"# Lakekeeper run report - {ledger['run_date']}",
        "",
        f"- **Run id**: `{ledger['run_id']}`",
        f"- **Status**: {ledger['status']}",
        f"- **Steps completed**: {len(ledger['steps_completed'])}",
        f"- **Rows quarantined**: {ledger['quarantined_total']}",
    ]
    verdict = ledger.get("verdict")
    if verdict:
        lines.append(f"- **Validation verdict**: {verdict['verdict']} - {verdict['explanation']}")
    findings = [
        r for report in ledger["dq_reports"] for r in report["results"] if r["failed_rows"] > 0
    ]
    if findings:
        lines += [
            "",
            "## Data-quality findings",
            "",
            "| table | rule | severity | rows |",
            "|---|---|---|---|",
        ]
        for report in ledger["dq_reports"]:
            for r in report["results"]:
                if r["failed_rows"]:
                    lines.append(
                        f"| {report['table']} | {r['rule_id']} | {r['severity']} "
                        f"| {r['failed_rows']}/{r['total_rows']} |"
                    )
    if ledger["decisions"]:
        lines += ["", "## Agent decisions", ""]
        for d in ledger["decisions"]:
            decision = d["decision"]
            summary = (
                decision.get("action")
                or decision.get("verdict")
                or ", ".join(f"{a['rule_id']}->{a['action']}" for a in decision.get("actions", []))
            )
            rationale = decision.get("rationale") or decision.get("explanation") or ""
            suffix = f" - {rationale}" if rationale else ""
            lines.append(f"- **{d['agent']}** ({d['mode']}): {summary}{suffix}")
    if ledger["failures"]:
        lines += ["", "## Failures", ""]
        lines += [f"- `{f['step']}`: {f['error']} - {f['message']}" for f in ledger["failures"]]
    lines += ["", "---", "_Generated by the Lakekeeper reporting agent (template mode)._"]
    return "\n".join(lines)


def make_node(ctx: AgentContext):
    def report(state: PipelineRunState) -> dict:
        final_status = "aborted" if state.get("status") == "aborted" else "done"
        ledger = _ledger(state)
        ledger["status"] = final_status
        writer = ctx.live_cheap
        if writer is not None:
            try:
                report_md = writer.generate_text(
                    REPORT_SYSTEM, json.dumps(ledger, default=str, indent=2)
                )
            except Exception:
                report_md = _template_report(ledger)
        else:
            report_md = _template_report(ledger)

        ctx.settings.reports_dir.mkdir(parents=True, exist_ok=True)
        stamp = datetime.now(UTC).strftime("%H%M%S")
        report_path = ctx.settings.reports_dir / f"report_{state['run_id']}_{stamp}.md"
        report_path.write_text(report_md, encoding="utf-8")
        ctx.console.print(f"  report written to [bold]{report_path}[/bold]")

        return {
            "plan": [],
            "report_md": report_md,
            "report_path": str(report_path),
            "status": final_status,
            "completed": [{"step": "report", "path": str(report_path)}],
        }

    return report
